# Generated by Django 5.2.5 on 2026-05-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
