# Generated by Django 5.2.5 on 2026-04-07 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0002_venta_comision_monto_venta_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del Cambio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_cambios', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Bitácora de Cambio',
                'verbose_name_plural': 'Bitácoras de Cambios',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cuota', models.PositiveIntegerField(verbose_name='No. Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Base (Capital)')),
                ('interes_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Interés')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_cobrar', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['venta', 'no_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('monto_mora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Mora')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Depósito', 'Depósito')], max_length=50, verbose_name='Método de Pago')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='cuentas_cobrar.cuota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin/Usuario que cobró')),
            ],
            options={
                'verbose_name': 'Pago Realizado',
                'verbose_name_plural': 'Pagos Realizados',
            },
        ),
    ]
