# Generated by Django 5.2.5 on 2026-04-22 19:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_cobrar', '0001_initial'),
        ('ventas', '0008_venta_cuotas_vencidas_calculado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacoracambio',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Cambio', 'verbose_name_plural': 'Historial de Cambios'},
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='interes_monto',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='monto_base',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto_pagado',
        ),
        migrations.AddField(
            model_name='bitacoracambio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_programada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Programada'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Cuota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Base'),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago'),
        ),
        migrations.AlterField(
            model_name='bitacoracambio',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción del Cambio'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido'), ('Revertido', 'Revertido')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='no_cuota',
            field=models.PositiveIntegerField(default=1, verbose_name='No. Cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Depósito', 'Depósito')], default='Efectivo', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cobró'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['venta', 'no_cuota'], name='ventas_cuot_venta_i_a82aec_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['estado', 'fecha_programada'], name='ventas_cuot_estado_5a0071_idx'),
        ),
        migrations.AlterModelTable(
            name='bitacoracambio',
            table='ventas_historialcambios',
        ),
        migrations.AlterModelTable(
            name='cuota',
            table='ventas_cuota',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='ventas_pago',
        ),
    ]
