# Generated by Django 5.2.5 on 2026-04-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_dpi_cliente_nit'),
        ('lotes', '0012_lote_unique_plano_svg_per_manzana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_lote', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor del Lote')),
                ('enganche', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Enganche')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('monto_financiar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Monto a Financiar')),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de Interés Anual (%)')),
                ('total_pagar_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total a Pagar Contado')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('FINANCIADO', 'Financiado')], default='FINANCIADO', max_length=20, verbose_name='Tipo de Pago')),
                ('plazo_meses', models.IntegerField(default=0, verbose_name='Plazo en Meses')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente', verbose_name='Cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='lotes.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_venta',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
