# Generated by Django 5.2.5 on 2026-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_liquidacioncomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='acepta_instalacion',
            field=models.BooleanField(default=False, verbose_name='Acepta Instalación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
