# Generated by Django 5.2.5 on 2026-04-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_dpi_cliente_nit'),
        ('lotes', '0013_remove_lote_lotes_manzana_estado_idx_and_more'),
        ('ventas', '0004_venta_acepta_instalacion_venta_forma_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prospecto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Prospecto')),
                ('telefono_prospecto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Prospecto')),
                ('valor_lote', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor del Lote')),
                ('enganche', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Enganche')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('monto_financiar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto a Financiar')),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de Interés Anual (%)')),
                ('total_pagar_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total a Pagar Contado')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('FINANCIADO', 'Financiado')], default='FINANCIADO', max_length=20, verbose_name='Tipo de Pago')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, verbose_name='Forma de Pago')),
                ('acepta_instalacion', models.BooleanField(default=False, verbose_name='Acepta Instalación')),
                ('plazo_meses', models.IntegerField(default=0, verbose_name='Plazo en Meses')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='lotes.lote', verbose_name='Lote')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'ventas_cotizacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
