# Generated by Django 5.2.5 on 2026-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
