# Generated by Django 5.2.5 on 2026-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('GENERADA', 'Generada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='GENERADA', max_length=20, verbose_name='Estado de la Venta'),
        ),
    ]
