# Generated by Django 5.2.5 on 2026-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuotas_vencidas_calculado',
            field=models.IntegerField(default=0, verbose_name='Cuotas Vencidas'),
        ),
        migrations.AddField(
            model_name='venta',
            name='saldo_pendiente_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Pendiente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_pagado_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Pagado'),
        ),
    ]
