# Generated by Django 5.2.5 on 2026-05-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_dpi_cliente_nit'),
        ('lotes', '0014_lotificacion_logo'),
        ('ventas', '0008_venta_cuotas_vencidas_calculado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Mensual')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Catálogo de Servicio',
                'verbose_name_plural': 'Catálogos de Servicios',
                'db_table': 'ventas_catalogo_servicio',
            },
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio_snapshot', models.CharField(max_length=150, verbose_name='Nombre del Servicio (Snapshot)')),
                ('costo_pactado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Pactado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='clientes.cliente', verbose_name='Cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='lotes.lote', verbose_name='Lote')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='ventas.catalogoservicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio Contratado',
                'verbose_name_plural': 'Servicios Contratados',
                'db_table': 'ventas_servicio_contratado',
            },
        ),
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Servicios')),
                ('monto_mora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto de Mora')),
                ('total_final', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='Total Final')),
                ('mes_referencia', models.DateField(db_index=True, verbose_name='Mes de Referencia')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_mensuales', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pago Mensual',
                'verbose_name_plural': 'Pagos Mensuales',
                'db_table': 'ventas_pago_mensual',
                'indexes': [models.Index(fields=['cliente', 'mes_referencia'], name='idx_cliente_mes_ref'), models.Index(condition=models.Q(('pagado', False)), fields=['pagado'], name='idx_pago_no_pagado')],
            },
        ),
    ]
