# Generated by Django 5.2.5 on 2026-05-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_catalogoservicio_serviciocontratado_pagomensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciocontratado',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='pagomensual',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='serviciocontratado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='serviciocontratado',
            name='lote',
        ),
        migrations.DeleteModel(
            name='CatalogoServicio',
        ),
        migrations.DeleteModel(
            name='PagoMensual',
        ),
        migrations.DeleteModel(
            name='ServicioContratado',
        ),
    ]
