# Generated by Django 5.2.5 on 2026-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_remove_serviciocontratado_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Depósito')], default='EFECTIVO', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Depósito')], default='EFECTIVO', max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
