# Generated by Django 5.2.5 on 2026-05-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0014_lotificacion_logo'),
        ('ventas', '0011_alter_cotizacion_forma_pago_alter_venta_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='lotes.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='lotes.lote', verbose_name='Lote'),
        ),
    ]
