# Generated by Django 5.2.5 on 2026-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_cotizacion_cliente_alter_cotizacion_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacioncomision',
            name='referencia_pago',
        ),
        migrations.AddField(
            model_name='liquidacioncomision',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Depósito')], max_length=20, null=True, verbose_name='Forma de Pago'),
        ),
    ]
