# Generated by Django 5.2.5 on 2025-08-21 17:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lotificacion', models.CharField(default='Lotificación San Carlos', max_length=200, verbose_name='Nombre de la Lotificación')),
                ('ubicacion', models.CharField(default='Villa Nueva, Guatemala', max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(default='Proyecto residencial con lotes de alta calidad en zona privilegiada', verbose_name='Descripción')),
                ('direccion_completa', models.TextField(default='Km 25 Carretera a El Salvador, Guatemala', verbose_name='Dirección Completa')),
                ('telefono', models.CharField(default='+502 2234-5678', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(default='info@lotificacionsancarlos.com', max_length=254, verbose_name='Email')),
                ('sitio_web', models.URLField(blank=True, default='www.lotificacionsancarlos.com', verbose_name='Sitio Web')),
                ('fecha_inicio', models.DateField(default='2024-01-15', verbose_name='Fecha de Inicio')),
                ('total_lotes', models.IntegerField(default=96, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Lotes')),
                ('area_total', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Área Total (m²)')),
                ('tasa_anual', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Tasa de interés anual en porcentaje', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tasa Anual (%)')),
                ('tasa_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.9489'), help_text='Tasa de interés mensual en porcentaje (calculada automáticamente)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('100.0000'))], verbose_name='Tasa Mensual (%)')),
                ('logo', models.ImageField(blank=True, help_text='Logo principal de la lotificación', null=True, upload_to='configuracion/logos/', verbose_name='Logo de la Empresa')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuraciones Generales',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo_minimo_meses', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Mínimo (meses)')),
                ('plazo_maximo_meses', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Máximo (meses)')),
                ('enganche_minimo_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Enganche Mínimo (%)')),
                ('enganche_maximo_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Enganche Máximo (%)')),
                ('costo_instalacion_default', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Instalación por Defecto (Q)')),
                ('permitir_pagos_anticipados', models.BooleanField(default=True, verbose_name='Permitir Pagos Anticipados')),
                ('aplicar_penalizacion_atrasos', models.BooleanField(default=True, verbose_name='Aplicar Penalización por Atrasos')),
                ('penalizacion_atraso_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Penalización por Atraso (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('configuracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_financiera', to='configuracion.configuraciongeneral')),
            ],
            options={
                'verbose_name': 'Configuración Financiera',
                'verbose_name_plural': 'Configuraciones Financieras',
            },
        ),
    ]
