# Generated by Django 5.2.5 on 2026-05-12 17:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_dpi_cliente_nit'),
        ('lotes', '0014_lotificacion_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleteraServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera_servicios', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Billetera de Servicio',
                'verbose_name_plural': 'Billeteras de Servicios',
                'db_table': 'servicios_billetera',
            },
        ),
        migrations.CreateModel(
            name='ServicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_base_defecto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Base Defecto')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono (String)')),
                ('es_recurrente', models.BooleanField(default=True, verbose_name='Es Recurrente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('lotificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_catalogo', to='lotes.lotificacion', verbose_name='Lotificación')),
            ],
            options={
                'verbose_name': 'Servicio de Catálogo',
                'verbose_name_plural': 'Servicios de Catálogo',
                'db_table': 'servicios_servicio_catalogo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_periodo', models.DateField(verbose_name='Mes del Periodo')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Cobrado')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Pagado')),
                ('mora_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Mora Aplicada')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('fecha_pago_realizado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago Realizado')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_servicios', to='lotes.lote', verbose_name='Lote')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='servicios.serviciocatalogo', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Pago de Servicio',
                'verbose_name_plural': 'Pagos de Servicios',
                'db_table': 'servicios_pago',
                'ordering': ['-mes_periodo', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionServicioLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Si es nulo, se usará el precio base del catálogo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Personalizado')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_servicios', to='lotes.lote', verbose_name='Lote')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_lotes', to='servicios.serviciocatalogo', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Configuración de Servicio por Lote',
                'verbose_name_plural': 'Configuraciones de Servicios por Lote',
                'db_table': 'servicios_configuracion_lote',
                'unique_together': {('lote', 'servicio')},
            },
        ),
    ]
