# Generated by Django 5.2.5 on 2026-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoservicio',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Depósito', 'Depósito'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
