# Generated by Django 5.2.5 on 2026-05-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_pagoservicio_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicios.serviciocatalogo', verbose_name='Servicio'),
        ),
    ]
