# Generated by Django 5.2.5 on 2026-04-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sueldo',
        ),
    ]
