# Generated by Django 5.2.5 on 2025-08-21 17:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=10, verbose_name='Número de Lote')),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Metros Cuadrados')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total (Q)')),
                ('enganche', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Enganche (Q)')),
                ('costo_instalacion', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10, verbose_name='Instalación (Q)')),
                ('plazo_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo (meses)')),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cuota Mensual (Q)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('en_proceso', 'En Proceso de Venta'), ('cancelado', 'Cancelado')], default='disponible', max_length=20, verbose_name='Estado del Lote')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['manzana', 'numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre de Manzana')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Nuevo Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='lotes.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Historial de Lote',
                'verbose_name_plural': 'Historial de Lotes',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='manzana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='lotes.manzana', verbose_name='Manzana'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('manzana', 'numero_lote')},
        ),
    ]
