# Generated by Django 5.2.5 on 2025-08-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('en_proceso', 'En Proceso de Venta'), ('financiado', 'Financiado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20, verbose_name='Estado del Lote'),
        ),
    ]
