# Generated by Django 5.2.5 on 2026-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_add_lotificacion_and_identificador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manzana',
            options={'ordering': ['lotificacion', 'nombre'], 'verbose_name': 'Manzana', 'verbose_name_plural': 'Manzanas'},
        ),
        migrations.AlterField(
            model_name='manzana',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Nombre de Manzana'),
        ),
        migrations.AlterUniqueTogether(
            name='manzana',
            unique_together={('lotificacion', 'nombre')},
        ),
    ]
