# Generated by Django - Remove enganche, plazo_meses, cuota_mensual from Lote

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_add_new_fields_to_lotificacion'),
    ]

    operations = [
        migrations.RemoveField(model_name='lote', name='enganche'),
        migrations.RemoveField(model_name='lote', name='plazo_meses'),
        migrations.RemoveField(model_name='lote', name='cuota_mensual'),
    ]
