# Generated by Django 5.2.5 on 2026-04-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_lotificacion_created_at_updated_at_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='identificador',
            field=models.CharField(blank=True, help_text='Identificador único que coincide con el id del path en el SVG (ej: MZ03-L07)', max_length=150, null=True, unique=True, verbose_name='Identificador SVG'),
        ),
    ]
