# Generated by Django 5.2.5 on 2026-04-03 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_alter_lote_identificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='plano_svg_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID textual exacto del SVG para sobreescribir la vinculacion dinamica', max_length=150, null=True, verbose_name='Plano SVG ID (Override)'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['plano_svg_id'], name='lotes_plano_svg_id_idx'),
        ),
    ]
