# Generated by Django 5.2.5 on 2026-04-03 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0011_lote_plano_svg_id_lote_lotes_plano_svg_id_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('manzana', 'plano_svg_id'), name='unique_plano_svg_per_manzana'),
        ),
    ]
