# Generated by Django 5.2.5 on 2026-04-06 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0012_lote_unique_plano_svg_per_manzana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lote',
            name='lotes_manzana_estado_idx',
        ),
        migrations.RemoveField(
            model_name='historiallote',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='historiallote',
            name='estado_nuevo',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='estado',
        ),
        migrations.AddField(
            model_name='historiallote',
            name='estado_disponibilidad_anterior',
            field=models.CharField(default='disponible', max_length=25, verbose_name='Estado Disp. Anterior'),
        ),
        migrations.AddField(
            model_name='historiallote',
            name='estado_disponibilidad_nuevo',
            field=models.CharField(default='disponible', max_length=25, verbose_name='Nuevo Estado Disp.'),
        ),
        migrations.AddField(
            model_name='lote',
            name='estado_disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('financiado', 'Financiado'), ('pagado', 'Pagado'), ('escriturado', 'Escriturado')], default='disponible', max_length=25, verbose_name='Estado de Disponibilidad'),
        ),
        migrations.AddField(
            model_name='lote',
            name='uso_lote',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial_y_bodega', 'Comercial y Bodega')], default='residencial', max_length=25, verbose_name='Uso del Lote'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['manzana', 'estado_disponibilidad'], name='lotes_manzana_estado_idx'),
        ),
    ]
