# Generated by Django 5.2.5 on 2026-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0013_remove_lote_lotes_manzana_estado_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotificacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='lotificaciones/logos/', verbose_name='Logotipo'),
        ),
    ]
