# Generated by Django 5.2.5 on 2025-08-22 00:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('fin_mes', 'Fin de Mes'), ('quincena', 'Quincena'), ('especifico', 'Día Específico')], max_length=20, verbose_name='Tipo de Pago')),
                ('dia_pago', models.PositiveIntegerField(help_text='Día del mes para el pago (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día de Pago')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
            },
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promitente_comprador', models.CharField(max_length=200, verbose_name='Promitente Comprador')),
                ('totalidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Totalidad')),
                ('enganche', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Enganche')),
                ('capital_cancelado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Capital Cancelado')),
                ('interes_cancelado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Interés Cancelado')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('plazo_meses', models.PositiveIntegerField(verbose_name='Plazo en Meses')),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cuota Mensual')),
                ('cuotas_canceladas', models.PositiveIntegerField(default=0, verbose_name='Cuotas Canceladas')),
                ('cuotas_pendientes', models.PositiveIntegerField(verbose_name='Cuotas Pendientes')),
                ('fecha_inicio_financiamiento', models.DateField(verbose_name='Fecha de Inicio del Financiamiento')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('en_mora', 'En Mora')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamientos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financiamientos_creados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financiamiento', to='lotes.lote')),
            ],
            options={
                'verbose_name': 'Financiamiento',
                'verbose_name_plural': 'Financiamientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Capital')),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Interés')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('atrasada', 'Atrasada'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('mora_atraso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Mora por Atraso')),
                ('dias_atraso', models.PositiveIntegerField(default=0, verbose_name='Días de Atraso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_creadas', to=settings.AUTH_USER_MODEL)),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='financiamiento.financiamiento')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['financiamiento', 'numero_cuota'],
                'unique_together': {('financiamiento', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Capital')),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Interés')),
                ('monto_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Mora')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_creados', to=settings.AUTH_USER_MODEL)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='financiamiento.cuota')),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='financiamiento.financiamiento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-fecha_creacion'],
            },
        ),
    ]
