# Generated by Django 5.2.5 on 2025-08-26 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('concepto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Concepto')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_capital_creados', to=settings.AUTH_USER_MODEL)),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_capital', to='financiamiento.financiamiento')),
            ],
            options={
                'verbose_name': 'Pago a Capital',
                'verbose_name_plural': 'Pagos a Capital',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
