# Generated by Django 5.2.5 on 2026-05-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0002_pagocapital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionPago',
        ),
    ]
